# .pre-commit-config.yaml
repos:
-   repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.33.0 # The version of cfn-lint to use
    hooks:
    -   id: cfn-python-lint
        name: CloudFormation Linter
        files: '(.*?)\.(cft)$'
